# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Laminar Flow
description:      'Time averaged stuff'
url:              http://nmcintosh.github.io

author:
  name:           'Nick McIntosh'

paginate:         5
